export const CATALOG = [
  {
    id: 'el1',
    name: 'Gibson Les Paul Standard 50s Tobacco Burst',
    img: '../../assets/img/el1.jpg',
    price: 2199,
  },
  {
    id: 'el2',
    name: 'Fender Player Stratocaster Polar White Maple Fingerboard',
    img: '../../assets/img/el2.jpg',
    price: 589,
  },
  {
    id: 'el3',
    name: 'Epiphone Les Paul Custom Koa Natural',
    img: '../../assets/img/el3.jpg',
    price: 599,
  },
  {
    id: 'el4',
    name: 'ESP E-II Horizon NT-7 Evertune Black',
    img: '../../assets/img/el4.jpg',
    price: 2399,
  },
  {
    id: 'el5',
    name: 'ESP LTD EC-1000 Vintage Black',
    img: '../../assets/img/el5.jpg',
    price: 999,
  },
  {
    id: 'el6',
    name: 'Fender FSR Tribute Stratocaster Fiesta Red (Limited Edition)',
    img: '../../assets/img/el6.jpg',
    price: 749,
  },
  {
    id: 'el7',
    name: 'Gibson Lzzy Hale Signature Explorerbird Cardinal RedEpiphone Les Paul Custom Koa Natural',
    img: '../../assets/img/el7.jpg',
    price: 2499,
  },
  {
    id: 'el8',
    name: 'ESP LTD Signature Alexi Laiho Ripped Purple Fade Satin',
    img: '../../assets/img/el8.jpg',
    price: 1699,
  },
  {
    id: 'el9',
    name: 'Fender FSR Tribute Stratocaster Black guitarguitar exclusive',
    img: '../../assets/img/el9.jpg',
    price: 749,
  },
  {
    id: 'el10',
    name: 'ESP LTD 30th Anniversary KH-3 Kirk Hammett Spider',
    img: '../../assets/img/el10.jpg',
    price: 1379,
  },
  {
    id: 'el11',
    name: 'Fender Player Telecaster Butterscotch Blonde Maple Fingerboard',
    img: '../../assets/img/el11.jpg',
    price: 589,
  },
  {
    id: 'el12',
    name: 'Fender Player Plus Stratocaster Tequila Sunrise Maple Fingerboard',
    img: '../../assets/img/el12.jpg',
    price: 799,
  },
  {
    id: 'el13',
    name: 'Epiphone Les Paul Standard 60s Iced Tea',
    img: '../../assets/img/el13.jpg',
    price: 549,
  },
  {
    id: 'el14',
    name: 'Gibson SG Standard Heritage Cherry',
    img: '../../assets/img/el14.jpg',
    price: 1399,
  },
  {
    id: 'el15',
    name: 'Gibson ES-335 Figured Sixties Cherry',
    img: '../../assets/img/el15.jpg',
    price: 3299,
  },
  {
    id: 'el16',
    name: 'Gibson Les Paul Standard 50s Tobacco Burst',
    img: '../../assets/img/el16.jpg',
    price: 2199,
  },
  {
    id: 'el17',
    name: 'Fender Limited Edition Vintera 70s Telecaster Thinline Shell Pink',
    img: '../../assets/img/el17.jpg',
    price: 999,
  },
  {
    id: 'el18',
    name: 'Fender Kurt Cobain Jaguar 3 Colour Sunburst NOS Left Handed Rosewood Fingerboard',
    img: '../../assets/img/el18.jpg',
    price: 1349,
  },
  {
    id: 'el19',
    name: 'Fender Player Plus Active Meteora Bass Opal Spark Pau Ferro Fingerboard',
    img: '../../assets/img/el19.jpg',
    price: 999,
  },
  {
    id: 'el20',
    name: 'Epiphone J-200EC Studio Vintage Natural',
    img: '../../assets/img/el20.jpg',
    price: 379,
  },
];