export const CATALOG = [
  {
    id: 'el1',
    name: 'Gibson Les Paul Standard 50s Tobacco Burst',
    img: '../../assets/img/el1.jpg',
    price: 2199,
    stock: 'Available',
    strings: 6,
    producer: 'Gibson',
    type: 'Electro',
    pickups: 'H-H',
    popular: true,
  },
  {
    id: 'el2',
    name: 'Fender Player Stratocaster Polar White Maple',
    img: '../../assets/img/el2.jpg',
    price: 589,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'S-S-S',
    popular: true,
  },
  {
    id: 'el3',
    name: 'Epiphone Les Paul Custom Koa Natural',
    img: '../../assets/img/el3.jpg',
    price: 599,
    stock: 'Available',
    strings: 6,
    producer: 'Epiphone',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el4',
    name: 'ESP E-II Horizon NT-7 Evertune Black',
    img: '../../assets/img/el4.jpg',
    price: 2399,
    stock: 'Available',
    strings: 7,
    producer: 'ESP',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el5',
    name: 'ESP LTD EC-1000 Vintage Black',
    img: '../../assets/img/el5.jpg',
    price: 999,
    stock: 'Available',
    strings: 6,
    producer: 'ESP',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el6',
    name: 'Fender FSR Tribute Stratocaster Fiesta Red',
    img: '../../assets/img/el6.jpg',
    price: 749,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'S-S-S',
    popular: true,
  },
  {
    id: 'el7',
    name: 'Gibson Lzzy Hale Signature Explorerbird Koa Natural',
    img: '../../assets/img/el7.jpg',
    price: 2499,
    stock: 'Available',
    strings: 6,
    producer: 'Gibson',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el8',
    name: 'ESP LTD Signature Alexi Laiho Purple Fade Satin',
    img: '../../assets/img/el8.jpg',
    price: 1699,
    stock: 'Not available',
    strings: 6,
    producer: 'ESP',
    type: 'Electro',
    pickups: 'S-H',
    popular: false,
  },
  {
    id: 'el9',
    name: 'Fender FSR Tribute Stratocaster Black',
    img: '../../assets/img/el9.jpg',
    price: 749,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'S-S-S',
    popular: true,
  },
  {
    id: 'el10',
    name: 'ESP LTD 30th Anniversary KH-3 Kirk Hammett Spider',
    img: '../../assets/img/el10.jpg',
    price: 1379,
    stock: 'Available',
    strings: 6,
    producer: 'ESP',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el11',
    name: 'Fender Player Telecaster Butterscotch Blonde Maple',
    img: '../../assets/img/el11.jpg',
    price: 589,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'S-S',
    popular: true,
  },
  {
    id: 'el12',
    name: 'Fender Player Stratocaster Tequila Sunrise',
    img: '../../assets/img/el12.jpg',
    price: 799,
    stock: 'Not available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'S-S-S',
    popular: true,
  },
  {
    id: 'el13',
    name: 'Epiphone Les Paul Standard 60s Iced Tea',
    img: '../../assets/img/el13.jpg',
    price: 549,
    stock: 'Available',
    strings: 6,
    producer: 'Epiphone',
    type: 'Electro',
    pickups: 'H-H',
    popular: true,
  },
  {
    id: 'el14',
    name: 'Gibson SG Standard Heritage Cherry',
    img: '../../assets/img/el14.jpg',
    price: 1399,
    stock: 'Available',
    strings: 6,
    producer: 'Gibson',
    type: 'Electro',
    pickups: 'H-H',
    popular: true,
  },
  {
    id: 'el15',
    name: 'Gibson ES-335 Figured Sixties Cherry',
    img: '../../assets/img/el15.jpg',
    price: 3299,
    stock: 'Available',
    strings: 6,
    producer: 'Gibson',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el16',
    name: 'Fender Custom Jazz Bass Heavy Relic Aged Black',
    img: '../../assets/img/el16.jpg',
    price: 4749,
    stock: 'Available',
    strings: 4,
    producer: 'Fender',
    type: 'Bass',
    pickups: 'H',
    popular: false,
  },
  {
    id: 'el17',
    name: 'Fender Vintera 70s Telecaster Shell Pink',
    img: '../../assets/img/el17.jpg',
    price: 999,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el18',
    name: 'Fender Kurt Cobain Jaguar Sunburst Left Handed',
    img: '../../assets/img/el18.jpg',
    price: 1349,
    stock: ' Not available',
    strings: 6,
    producer: 'Fender',
    type: 'Electro',
    pickups: 'H-H',
    popular: false,
  },
  {
    id: 'el19',
    name: 'Fender Player Plus Meteora Bass Opal Spark',
    img: '../../assets/img/el19.jpg',
    price: 999,
    stock: 'Available',
    strings: 4,
    producer: 'Fender',
    type: 'Bass',
    pickups: 'H-H',
    popular: true,
  },
  {
    id: 'el20',
    name: 'Epiphone J-200EC Studio Vintage Natural',
    img: '../../assets/img/el20.jpg',
    price: 379,
    stock: 'Available',
    strings: 6,
    producer: 'Epiphone',
    type: 'Acoustic',
    pickups: 'None',
    popular: false,
  },
  {
    id: 'el21',
    name: 'Fender CD-60SCE Natural Walnut Fingerboard',
    img: '../../assets/img/el21.jpg',
    price: 239,
    stock: 'Available',
    strings: 6,
    producer: 'Fender',
    type: 'Acoustic',
    pickups: 'None',
    popular: true,
  },
];